### ISSUE TITLE
Feature request: colors!!!!

### ISSUE THREAD

**Issue by kiernanmcgowan** [kanatzidis/nyan#1]
This needs to use command line colors to make a rainbow explosion.

**Comment by kanatzidis** [comment]
yes it does. The app I stole the frames from does coloring so I'll probably steal that logic.

**Comment by piranna** [comment]
Any update on that? I want colors too! :-D

**Comment by kanatzidis** [comment]
:grinning: Your wish is my command: https://github.com/kanatzidis/nyan/pull/2
